### ISSUE TITLE
some questions about the parameters in MPC controler

### ISSUE THREAD

**Issue by CrisFLZs** [bitfsd/fsd_algorithm#1]
Sorry to bother u, i have some questions about the meanings of the parameters in MPC controler. I don't understand the 'cte' and 'epsi',could u please give me a explanation.Thank u·

**Comment by Feng1909** [comment]
Hello, we assume the 'cte' represents the lateral deviation between car and the reference path, and 'epsi' represents the angle between vehicle and road center line.

**Comment by CrisFLZs** [comment]
Thank u so much~ Now I understand those parameters
