### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by WangLu180** [bitfsd/fsd_algorithm#2]
请问，编译成功运行后报错
1.“[automated_res-2] process has died [pid 6271, exit code 1, cmd /home/luwang/catkin_qwe/src/fssim/fssim/scripts/automated_res.py --config /home/luwang/catkin_qwe/src/fssim/fssim/config/simulation.yaml __name:=automated_res __log:=/home/luwang/.ros/log/5cd8425c-96a8-11eb-82b9-98541b1c7b0e/automated_res-2.log].
log file: /home/luwang/.ros/log/5cd8425c-96a8-11eb-82b9-98541b1c7b0e/automated_res-2*.log
”
2.[ WARN] [1617693607.918814052]: Did not load transform_matrix_topic_name. Standard value is: /transform_matrix
[ WARN] [1617693607.919145947]: Did not load end_point_topic_name. Standard value is: /planning/end_point
[ INFO] [1617693607.921403620]: subscribe to topics
[ INFO] [1617693607.928647283]: publish to topics
[ WARN] [1617693607.931245868]: Local Map Empty !
[ WARN] [1617693607.931282874]: Check Error
是什么原因那？是没有加载地图吗？

**Comment by Feng1909** [comment]
1.请问是使用catkin build命令编译的吗
2.仿真未正确开启或未开启fssim_interface均会报此错误

**Comment by WangLu180** [comment]
已经解决了，谢谢，fssim 依赖安装有问题
