### ISSUE TITLE
启动仿真报错

### ISSUE THREAD

**Issue by KeepFighting69** [bitfsd/fsd_algorithm#3]
编译成功后，启动仿真时遇到以下问题（Rviz界面有打开）：
ImportError: No module named fssim.shell
[automated_res-2] process has died [pid 64537, exit code 1, cmd /home/crd/Workspace/FSSIM_simulator/src/fssim/scripts/automated_res.py --config /home/crd/Workspace/FSSIM_simulator/src/fssim/config/simulation.yaml __name:=automated_res __log:=/home/crd/.ros/log/bdfdfffe-9cc0-11eb-b08b-000c29357aee/automated_res-2.log].
log file: /home/crd/.ros/log/bdfdfffe-9cc0-11eb-b08b-000c29357aee/automated_res-2*.log
libGL error: failed to create drawable
libGL error: failed to create drawable
请问大佬，该如何解决？

**Comment by Feng1909** [comment]
请问是使用catkin build命令编译的吗，是如何开启仿真的？

**Comment by KeepFighting69** [comment]
> 请问是使用catkin build命令编译的吗，是如何开启仿真的？

是使用catkin build命令编译的；

使用如下命令开启仿真的：
crd@crd-virtual-machine:~/Workspace/FSSIM_simulator$ source devel/setup.bash
crd@crd-virtual-machine:~/Workspace/FSSIM_simulator$ roslaunch fssim auto_fssim.launch

**Comment by chentairan** [comment]
Hi @KeepFighting69 

There are two errors in your issue.
```
ImportError: No module named fssim.shell
libGL error: failed to create drawable
```
Please check your Python and libGL environment.
And do not try to use the virtual machine to run fssim. We strongly recommend running on a full Ubuntu 18.04 system.

Tairan Chen

**Comment by WangLu180** [comment]
请问boost库用的是哪个版本的？我在编译的时候遇到了找不到boost_signals的错误
