### ISSUE TITLE
MPC

### ISSUE THREAD

**Issue by WangLu180** [bitfsd/fsd_algorithm#4]
请问如果要把纯跟踪改为mpc，除了修改control下的config的yaml文件controller设置为mpc，对fssim还需要其他更改吗？

**Comment by Feng1909** [comment]
不需要，直接运行就可以

**Comment by WangLu180** [comment]
直接运行在控制终端会有以下报错：
process[control_node-1]: started with pid [5739]
[ INFO] [1618891182.414953976]: Constructing Handle
[ INFO] [1618891182.416433667]: loading handle parameters
[ WARN] [1618891182.424500572]: Did not load transform_matrix_topic_name. Standard value is: /transform_matrix
[ WARN] [1618891182.425235119]: Did not load end_point_topic_name. Standard value is: /planning/end_point
[ INFO] [1618891182.434396217]: subscribe to topics
[ INFO] [1618891182.466040792]: publish to topics
[ WARN] [1618891182.489174073]: Local Map Empty !
[ WARN] [1618891182.489208160]: Check Error
time cost = 0.000126368, frequency = 7913.4
[ WARN] [1618891182.611583323, 1352.027000000]: Local Map Empty !
[ WARN] [1618891182.611655554, 1352.027000000]: Check Error
time cost = 0.000124684, frequency = 8020.28
[ INFO] [1618891182.734719368, 1352.122000000]: set state
[ INFO] [1618891182.735202127, 1352.122000000]: finish set state
[ INFO] [1618891182.735656000, 1352.122000000]: set solver trajectory
[ INFO] [1618891182.736094904, 1352.122000000]: begin solve
fg: 241
vars: 318
Cost 6.95312e-310
cppad-20180000.0 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 476 in the file 
    /usr/include/cppad/utility/vector.hpp
control: /usr/include/cppad/utility/error_handler.hpp:206: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
[control_node-1] process has died [pid 5739, exit code -6, cmd /home/luwang/catkin_qw/devel/lib/control/control __name:=control_node __log:=/home/luwang/.ros/log/c576ebbc-a18c-11eb-bdd0-98541b1c7b0e/control_node-1.log].
log file: /home/luwang/.ros/log/c576ebbc-a18c-11eb-bdd0-98541b1c7b0e/control_node-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
请问该如何解决那？十分感谢

**Comment by Feng1909** [comment]
请使用script文件夹下的ipopt安装脚本使用sudo bash进行安装

**Comment by CrisFLZs** [comment]
你好，我也遇到了同样的问题，而且script文件夹下的ipopt安装脚本使用sudo bash进行安装，依然会出现相同报错，请问有什么解决办法么，非常感谢。

**Comment by Feng1909** [comment]
我测试的时候遇到过一模一样的错误，方便留下联系方式吗，我是通过重装ipopt解决的，可以尝试将install_ipopt.bash里的命令在命令行中单独运行，应该会有其他的报错提示

**Comment by Feng1909** [comment]
将文件内容替换如下试试呢
#!/bin/bash
# Pass the Ipopt source directory as the first argument
if [ -z $1 ]
then
    echo "Specifiy the location of the Ipopt source directory in the first argument."
    exit
fi
cd $1

prefix=/usr/local
srcdir=$PWD

echo "Building Ipopt from ${srcdir}"
echo "Saving headers and libraries to ${prefix}"

# BLAS
cd $srcdir/ThirdParty/Blas
./get.Blas
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic
make install

# Lapack
cd $srcdir/ThirdParty/Lapack
./get.Lapack
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran"
make install

# ASL
cd $srcdir//ThirdParty/ASL
./get.ASL

# MUMPS
cd $srcdir/ThirdParty/Mumps
./get.Mumps

# build everything
cd $srcdir
./configure --prefix=$prefix coin_skip_warn_cxxflags=yes \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran" \
    --with-lapack=$prefix/lib/libcoinlapack.a
make
make test
make -j1 install

**Comment by Feng1909** [comment]
将文件内容替换如下试试呢
```
#!/bin/bash
# Pass the Ipopt source directory as the first argument
if [ -z $1 ]
then
    echo "Specifiy the location of the Ipopt source directory in the first argument."
    exit
fi
cd $1

prefix=/usr/local
srcdir=$PWD

echo "Building Ipopt from ${srcdir}"
echo "Saving headers and libraries to ${prefix}"

# BLAS
cd $srcdir/ThirdParty/Blas
./get.Blas
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic
make install

# Lapack
cd $srcdir/ThirdParty/Lapack
./get.Lapack
mkdir -p build && cd build
../configure --prefix=$prefix --disable-shared --with-pic \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran"
make install

# ASL
cd $srcdir//ThirdParty/ASL
./get.ASL

# MUMPS
cd $srcdir/ThirdParty/Mumps
./get.Mumps

# build everything
cd $srcdir
./configure --prefix=$prefix coin_skip_warn_cxxflags=yes \
    --with-blas="$prefix/lib/libcoinblas.a -lgfortran" \
    --with-lapack=$prefix/lib/libcoinlapack.a
make
make test
make -j1 install
```

**Comment by WangLu180** [comment]
出现报错后我也是使用script下脚本安装，但是提示已安装运行还是报错，之后将ipopt删除重装，关于ipopt的报错解决，但是主算法编译又出现了问题，提示ipopt缺少内容

**Comment by Feng1909** [comment]
> 出现报错后我也是使用script下脚本安装，但是提示已安装运行还是报错，之后将ipopt删除重装，关于ipopt的报错解决，但是主算法编译又出现了问题，提示ipopt缺少内容

使用我刚刚发的那个脚本试试呢？也还是报错吗

**Comment by Feng1909** [comment]
> 出现报错后我也是使用script下脚本安装，但是提示已安装运行还是报错，之后将ipopt删除重装，关于ipopt的报错解决，但是主算法编译又出现了问题，提示ipopt缺少内容

缺少`BLAS` `Lapack` `ASL` `MUMPS`之类的吗

**Comment by CrisFLZs** [comment]
非常感谢，我用该脚本重新安装ipopt后解决了，同时安装过程参考了https://github.com/udacity/CarND-MPC-Quizzes/blob/master/install_Ipopt_CppAD.md，提供给有需求的人

**Comment by Feng1909** [comment]
> 非常感谢，我用该脚本重新安装ipopt后解决了，同时安装过程参考了[https://github.com/udacity/CarND-MPC-Quizzes/blob/master/install_Ipopt_CppAD.md，提供给有需求的人](https://github.com/udacity/CarND-MPC-Quizzes/blob/master/install_Ipopt_CppAD.md%EF%BC%8C%E6%8F%90%E4%BE%9B%E7%BB%99%E6%9C%89%E9%9C%80%E6%B1%82%E7%9A%84%E4%BA%BA)

好的非常感谢，应该是我们测试的时候出现疏忽。

**Comment by WangLu180** [comment]
@CrisFLZs @Feng1909 方便留下联系方式吗？或者建立一个群聊，方便交流(微信号：15668778143)

**Comment by chentairan** [comment]
Hi @WangLu180 

We hope to discuss the algorithm on GitHub so that more people can see it. Right now we have no plan to set up a group.

Best Tairan Chen

**Comment by WangLu180** [comment]
@chentairan All right.You have thought comprehensively. Thank you.
