### ISSUE TITLE
编译错误丢包

### ISSUE THREAD

**Issue by HJCMOTOR** [bitfsd/fsd_algorithm#5]
在work1（工作区1） 中使用catkin build编译后提示错误信息丢包和错误,请问我应该如何解决，报错信息如下

Errors     << robot_localization:cmake /home/zzh/work1/logs/robot_localization/build.cmake.004.log
robot_localization: You did not request a specific build type: selecting 'RelWithDebInfo'.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "geographic_msgs"
  with any of the following names:

    geographic_msgsConfig.cmake
    geographic_msgs-config.cmake

  Add the installation prefix of "geographic_msgs" to CMAKE_PREFIX_PATH or
  set "geographic_msgs_DIR" to a directory containing one of the above files.
  If "geographic_msgs" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)

cd /home/zzh/work1/build/robot_localization; catkin build --get-env robot_localization | catkin env -si  /usr/bin/cmake /home/zzh/work1/src/estimation/robot_localization --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/zzh/work1/devel/.private/robot_localization -DCMAKE_INSTALL_PREFIX=/home/zzh/work1/install; cd -
...............................................................................
Failed     << robot_localization:cmake          [ Exited with code 1 ]         
Failed    <<< robot_localization                [ 1.4 seconds ]                
Abandoned <<< skidpad_detector                  [ Unrelated job failed ]       
Abandoned <<< darknet_ros                       [ Unrelated job failed ]       
Abandoned <<< boundary_detector                 [ Unrelated job failed ]       
Abandoned <<< fssim_interface                   [ Unrelated job failed ]       
Abandoned <<< lidar_cluster                     [ Unrelated job failed ]       
Abandoned <<< control                           [ Unrelated job failed ]       
[build] Summary: 8 of 15 packages succeeded.                                   
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 6 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 10.0 seconds total.

**Comment by Feng1909** [comment]
请尝试运行命令`sudo apt-get install ros-melodic-geographic-msgs`，本错误是由于您的运行环境缺少依赖。

**Comment by HJCMOTOR** [comment]
成功运行了，非常感谢！😘
