### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by KQ1027** [bitfsd/fsd_algorithm#6]
想问一下最近还有更新的打算么？代码有点吃不透呀，看了好久好久，大概摸清了各模块，但是还是吃不透，有打算进一步注释么？
另外，control模块按照步骤安装IPOPT后，还是报错，无法找到，有解决办法么

**Comment by Feng1909** [comment]
请贴一下详细报错信息呢，以及安装方式和运行报错的命令？

**Comment by WHcrown** [comment]
抱歉，在忙别的项目，这个暂时不会更新注释了，请关注北京理工大学无人车队的开源代码，并寻求帮助。希望以上信息能帮助到你。附上FSAC开源平台公众号链接，https://mp.weixin.qq.com/s/DVFNAergHdBjRw8nesvIQA




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitfsd/fsd_algorithm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 下午4:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bitfsd/fsd_algorithm] hello (Issue #6)





 
想问一下最近还有更新的打算么？代码有点吃不透呀，看了好久好久，大概摸清了各模块，但是还是吃不透，有打算进一步注释么？
 另外，control模块按照步骤安装IPOPT后，还是报错，无法找到，有解决办法么

**Comment by KQ1027** [comment]
稍等，没想到回复这么快，我刚把所有的项目内容删除了重新部署

**Comment by KQ1027** [comment]
&nbsp; &nbsp; &nbsp; 收到，非常感谢您们的付出，这些公众号或官网或github资源我都看过了，目前还是对这个代码架构不清晰，自身能力不足，我再继续努力。
&nbsp; &nbsp; &nbsp;如果有其他内容讲解资料、相关资料或相关学习课程、学习方法路线，非常渴望得到您的推荐，谢谢。
&nbsp; &nbsp; &nbsp;再次感谢您的回复，希望能再次与您交流。祝学业顺利，工作顺利。



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 8, 2023 16:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bitfsd/fsd_algorithm] hello (Issue #6)




 抱歉，在忙别的项目，这个暂时不会更新注释了，请关注北京理工大学无人车队的开源代码，并寻求帮助。希望以上信息能帮助到你。附上FSAC开源平台公众号链接，https://mp.weixin.qq.com/s/DVFNAergHdBjRw8nesvIQA 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "bitfsd/fsd_algorithm"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月8日(星期六) 下午4:36 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[bitfsd/fsd_algorithm] hello (Issue #6) 
 
 
 
 
 
   
 想问一下最近还有更新的打算么？代码有点吃不透呀，看了好久好久，大概摸清了各模块，但是还是吃不透，有打算进一步注释么？ 
  另外，control模块按照步骤安装IPOPT后，还是报错，无法找到，有解决办法么

**Comment by WHcrown** [comment]
这个是北理团队中一个非常nice的同学，具体问题可与他取得联系。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitfsd/fsd_algorithm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitfsd/fsd_algorithm] hello (Issue #6)





 &amp;nbsp; &amp;nbsp; &amp;nbsp; 收到，非常感谢您们的付出，这些公众号或官网或github资源我都看过了，目前还是对这个代码架构不清晰，自身能力不足，我再继续努力。 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;如果有其他内容讲解资料、相关资料或相关学习课程、学习方法路线，非常渴望得到您的推荐，谢谢。 
 &amp;nbsp; &amp;nbsp; &amp;nbsp;再次感谢您的回复，希望能再次与您交流。祝学业顺利，工作顺利。 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Sat, Apr 8, 2023 16:45 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [bitfsd/fsd_algorithm] hello (Issue #6) 
 
 
 
 
  抱歉，在忙别的项目，这个暂时不会更新注释了，请关注北京理工大学无人车队的开源代码，并寻求帮助。希望以上信息能帮助到你。附上FSAC开源平台公众号链接，https://mp.weixin.qq.com/s/DVFNAergHdBjRw8nesvIQA  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "bitfsd/fsd_algorithm"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年4月8日(星期六) 下午4:36  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[bitfsd/fsd_algorithm] hello (Issue #6)  
   
   
   
   
   
     
  想问一下最近还有更新的打算么？代码有点吃不透呀，看了好久好久，大概摸清了各模块，但是还是吃不透，有打算进一步注释么？  
   另外，control模块按照步骤安装IPOPT后，还是报错，无法找到，有解决办法么

**Comment by KQ1027** [comment]
![图片](https://user-images.githubusercontent.com/115533042/230713148-91c41339-9d4a-425c-975a-2a8e411f2b9f.png
您好，报错内容如图，control包内已经按照readme步骤执行，其余两包是代码问题么？

**Comment by Feng1909** [comment]
您的截图看起来是ros的pcl库安装存在问题，不涉及ipopt

**Comment by shuangji-66** [comment]
ipopt安装报错可以考虑apt安装，csdn搜一下就有，很方便
