### ISSUE TITLE
请问FSSIM有轮胎模型吗，可以用动力学模型进行跟踪吗

### ISSUE THREAD

**Issue by shuangji-66** [bitfsd/fsd_algorithm#7]

**Comment by Feng1909** [comment]
您好，不太清楚您问的是仿真还是控制，仿真中fssim是有轮胎模型的：https://github.com/bitfsd/fssim/blob/main/fssim_gazebo_plugins/gazebo_race_car_model/src/wheel.cpp
在控制层面是可以用基于动力学模型的模型预测控制算法进行跟踪的，轮胎力均使用魔术公式进行拟合
