### ISSUE TITLE
您好，请问在得到yolo目标检测框和点云聚类处理后，是怎么得到锥桶位置信息用于边界检测的啊？

### ISSUE THREAD

**Issue by ChunQiuBC** [bitfsd/fsd_algorithm#8]
您好，请问在得到yolo目标检测框和进行点云聚类处理后，是怎么得到锥桶位置信息用于边界检测的啊？这里有用到相机和激光雷达的融合感知吗？

**Comment by Feng1909** [comment]
根据相机和雷达的外参标定后的旋转平移矩阵，将检测框与聚类锥桶进行匹配，然后通过boundary detector进行边界检测，此时锥桶信息包含聚类的坐标和检测框的颜色，以此完成数据融合

**Comment by ChunQiuBC** [comment]
> 根据相机和雷达的外参标定后的旋转平移矩阵，将检测框与聚类锥桶进行匹配，然后通过boundary detector进行边界检测，此时锥桶信息包含聚类的坐标和检测框的颜色，以此完成数据融合

感谢！终于清楚了，不过在源码里好像没有包含数据融合这一部分？还有我想请教一下boundary detector节点接收的Map.msg表示的是锥桶的绝对位置还是车辆坐标系下的位置...？

**Comment by Feng1909** [comment]
由于各个车队的硬件方案并不相通，因此没有提供融合程序。boundary detector的输入地图为车辆坐标系地图

**Comment by ChunQiuBC** [comment]
> 由于各个车队的硬件方案并不相通，因此没有提供融合程序。boundary detector的输入地图为车辆坐标系地图

好的，感谢再次回复，期待再次与您交流，祝您生活愉快~
