### ISSUE TITLE
请问使用rtk定位的话还需要建图吗？

### ISSUE THREAD

**Issue by ChunQiuBC** [bitfsd/fsd_algorithm#9]
您好，请问使用rtk定位的话还需要建立点云地图吗？我考虑使用rtk进行定位，然后采用建图的办法将感知模块得到的锥筒坐标点记录下来，作为全局地图，直接用于第二圈的规划，这种办法可行吗？

**Comment by Feng1909** [comment]
可行的，地图中的信息可以仅包含锥桶的位置和颜色，如果要用雷达点云进行建图，算力的开支会非常高。
